# You have to configure this ###################################################
title: Hardcode
# You should configure this ####################################################
url: https://hardcode.fm
download_url: "https://hardcode.fm/"
subtitle: Подкаст о практике программирования
description: Записываемся на утюг (пока что)
author: Vlad Bokov
author_url: "https://razum2um.me" # This is the URL of a site owned by the author (s. https://jsonfeed.org/version/1)
email: vlad@razum2um.me
keywords: [podcast, ruby, javascript, clojure]
itunes_categories: [Technology]
# additional_feeds:
#   itunes: http://itunes.apple.com/de/podcast/podcast_name/id42424242
#   torrent_m4a: http://bitlove.org/example_user/example_podcast_m4a/feed
#   torrent_mp3: http://bitlove.org/example_user/example_podcast_mp3/feed
episodes_per_feed_page: 100
# Date can be localized via date_de.rb plugin
date_format: "ordinal"
## Rsync Deploy config #########################################################
### Be sure your public key is listed in your server's ~/.ssh/authorized_keys
### file.
ssh_host: hardcode@hardcode.fm
ssh_port: 2223
document_root: /home/hardcode/hardcode
rsync_delete: true
# You can configure this #######################################################
twitter_nick: hardcodefm
language: ru
explicit: 'no'  # 'yes'/'no'/clean
license: CC BY 4.0
## Flattr ######################################################################
flattr_uid: # Flattr will not be used unless this is set
flattr_button: compact # compact | default
flattr_mode: auto # auto | manual(default)
flattr_popout:  1 # 1 | 0 (show popout when hovering mouse over button)
flattr_language: en_GB # available languages - https://api.flattr.com/rest/v2/languages.txt
flattr_category: audio # available categories - https://api.flattr.com/rest/v2/categories.txt
## Disqus comments #############################################################
disqus_shortname: # Disqus will not be used unless this is set
disqus_developer: 0 # 1 / 0
## Itunes link ###########################################################
itunes_url: "https://itunes.apple.com/at/podcast/myname/id#myid#"
## Isso comments #########################################################
use_isso: no # set to 'yes' to include isso comments form

plugins: [jekyll-octopod]
theme: jekyll-bootflat
